### PR TITLE
add a simple vtf test

### PR DESCRIPTION
**Pull request by akva2**
This add an example vtf test.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this ifem=271 please

**Comment by akva2** [comment]
jenkins build this ifem=271 please

**Comment by akva2** [comment]
jenkins build this ifem=271 please

**Comment by akva2** [comment]
jenkins build this ifem=271 please

**Comment by akva2** [comment]
jenkins build this ifem=271 please

**Comment by akva2** [comment]
jenkins build this ifem=271 please

**Comment by akva2** [comment]
jenkins build this ifem=271 please

**Comment by kmokstad** [comment]
Did you forget this one @akva2 or is more coming?

**Comment by akva2** [comment]
both ;)

**Pull request merged**
