### PR TITLE
Reaction forces

### PR DESCRIPTION
**Pull request by kmokstad**
Revisited some work done long time ago on calculation of reaction forces for linear problems.
This seems to work well now, such that the External energy printed now makes sense.
Requires OPM/IFEM#343

### CODE REVIEW

**Comment by kmokstad** [comment]
jenkins build this ifem=343 please

**Comment by kmokstad** [comment]
There is a small issue here regarding the MPI test. If trying to activate external energy calculation there, through the `<reactions\>' tag, the calculated energy for the _second_ mesh is as before this fix, whereas for the initial mesh is becomes as for the serial case. So can there be something the with reaction force implementation that do not work for parallel LR-meshes? Due to this issue, the calculation is switched off for the affected Waterfall3D model. Consider a revisit later.

**Comment by akva2** [comment]
It should not make a difference there as long as the element groups are ignored in the assembly of the reactions. Only proc 0 should do the integration.

**Comment by kmokstad** [comment]
jenkins build this ifem=343 please

**Pull request merged**
